files:
  include:
    - 'src/**/*.s+(a|c)ss'

rules:
  placeholder-in-extend:
    - 0

  no-color-literals:
    - 0

  final-newline:
    - 0

  space-after-comma:
    - 0

  force-attribute-nesting:
    - 0

  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true

  no-vendor-prefixes:
    - 0

  force-element-nesting:
    - 0

  force-pseudo-nesting:
    - 0

  class-name-format:
    - 1
    - convention: strictbem

  nesting-depth:
    - 1
    - max-depth: 3

  property-sort-order:
    - 0